# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from controllers.Manager import AlarmManager
from subprocess import Popen
from functools import partial

class Ui_MainWindow(QtWidgets.QMainWindow):

    def reloadAlarms(self, layout):
        while layout.count():
            child = layout.takeAt(0)
            if child.widget() is not None:
                child.widget().deleteLater()
            elif child.layout() is not None:
                self.clearTasks(child.layout(), None)

        self.showActiveAlarms()

    def stopSpecificAlarm(self, id_):
        AlarmManager.removeAlarm(id_)
        self.reloadAlarms(self.alarmsHorizontalLayout)

    def getDefaultAlarmFrame(self, data):
        self.alarmFrame = QtWidgets.QFrame()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alarmFrame.sizePolicy().hasHeightForWidth())
        self.alarmFrame.setSizePolicy(sizePolicy)
        self.alarmFrame.setMinimumSize(QtCore.QSize(150, 200))
        self.alarmFrame.setStyleSheet("background-color: rgb(255, 125, 238);")
        self.alarmFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.alarmFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alarmFrame.setObjectName("alarmFrame")
        self.specificAlarmTitle = QtWidgets.QLabel(self.alarmFrame)
        self.specificAlarmTitle.setGeometry(QtCore.QRect(0, 20, 150, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.specificAlarmTitle.setFont(font)
        self.specificAlarmTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.specificAlarmTitle.setText(data['title'])
        self.specificAlarmTitle.setObjectName("specificAlarmTitle")
        self.specificAlarmTime = QtWidgets.QLabel(self.alarmFrame)
        self.specificAlarmTime.setGeometry(QtCore.QRect(0, 50, 150, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.specificAlarmTime.setFont(font)
        self.specificAlarmTime.setAlignment(QtCore.Qt.AlignCenter)
        self.specificAlarmTime.setObjectName("specificAlarmTime")
        self.specificAlarmTime.setText(data['time'])
        self.stopAlarmButton = QtWidgets.QPushButton(self.alarmFrame)
        self.stopAlarmButton.setGeometry(QtCore.QRect(40, 140, 75, 23))
        self.stopAlarmButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stopAlarmButton.setObjectName("stopAlarmButton")
        self.stopAlarmButton.setText("Parar")
        self.stopAlarmButton.clicked.connect(partial(self.stopSpecificAlarm, data['ID']))

        return self.alarmFrame

    def showActiveAlarms(self):
        alarms = AlarmManager.getAll()

        for a in alarms:
            alarmFrame = self.getDefaultAlarmFrame(a)
            self.alarmsHorizontalLayout.addWidget(alarmFrame)

    def checkFields(self, list_):
        for i in list_:
            if i.replace(' ', '') == '':
                return False
        return True

    def startNewAlarm(self):
        title = self.alarmTitle.text()
        timeData = self.hourAlarm.text() + ':' + self.minuteAlarm.text() + ':' + self.secondAlarm.text()
        
        if not self.checkFields(timeData.split(':')):
            QtWidgets.QMessageBox.about(self, 'Erro', 'Formato de horas incorreto')
        else:
            data = {
                'title': title,
                'hour': timeData
            }
            
            Popen(["pythonw", "controllers/WaitHour.pyw", data['title'], data['hour']], shell=False)
            self.reloadAlarms(self.alarmsHorizontalLayout)
            QtWidgets.QMessageBox.about(self, 'Sucesso', 'Alarme inicializado!')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 9, 681, 101))
        self.frame.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.alarmTitle = QtWidgets.QLineEdit(self.frame)
        self.alarmTitle.setGeometry(QtCore.QRect(10, 60, 281, 31))
        self.alarmTitle.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.alarmTitle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.alarmTitle.setObjectName("alarmTitle")
        self.hourAlarm = QtWidgets.QLineEdit(self.frame)
        self.hourAlarm.setGeometry(QtCore.QRect(360, 60, 61, 31))
        self.hourAlarm.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.hourAlarm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.hourAlarm.setObjectName("hourAlarm")
        self.minuteAlarm = QtWidgets.QLineEdit(self.frame)
        self.minuteAlarm.setGeometry(QtCore.QRect(450, 60, 61, 31))
        self.minuteAlarm.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.minuteAlarm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.minuteAlarm.setObjectName("minuteAlarm")
        self.secondAlarm = QtWidgets.QLineEdit(self.frame)
        self.secondAlarm.setGeometry(QtCore.QRect(540, 60, 61, 31))
        self.secondAlarm.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.secondAlarm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.secondAlarm.setObjectName("secondAlarm")
        self.dots = QtWidgets.QLabel(self.frame)
        self.dots.setGeometry(QtCore.QRect(430, 60, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dots.setFont(font)
        self.dots.setAlignment(QtCore.Qt.AlignCenter)
        self.dots.setObjectName("dots")
        self.dots_2 = QtWidgets.QLabel(self.frame)
        self.dots_2.setGeometry(QtCore.QRect(520, 60, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dots_2.setFont(font)
        self.dots_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dots_2.setObjectName("dots_2")
        self.defineAlarm = QtWidgets.QPushButton(self.frame)
        self.defineAlarm.setGeometry(QtCore.QRect(630, 60, 41, 31))
        self.defineAlarm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.defineAlarm.setObjectName("defineAlarm")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.scrollAreaAlarms = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaAlarms.setGeometry(QtCore.QRect(9, 129, 681, 251))
        self.scrollAreaAlarms.setWidgetResizable(True)
        self.scrollAreaAlarms.setObjectName("scrollAreaAlarms")
        self.scrollAreaAlarmsWidget = QtWidgets.QWidget()
        self.scrollAreaAlarmsWidget.setGeometry(QtCore.QRect(0, 0, 679, 249))
        self.scrollAreaAlarmsWidget.setObjectName("scrollAreaAlarmsWidget")
        self.alarmsHorizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaAlarmsWidget)
        self.alarmsHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.alarmsHorizontalLayout.setObjectName("alarmsHorizontalLayout")
        self.scrollAreaAlarms.setWidget(self.scrollAreaAlarmsWidget)
        MainWindow.setCentralWidget(self.centralwidget)


        self.defineAlarm.clicked.connect(self.startNewAlarm)
        self.showActiveAlarms()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dots.setText(_translate("MainWindow", ":"))
        self.dots_2.setText(_translate("MainWindow", ":"))
        self.defineAlarm.setText(_translate("MainWindow", "✔️"))
        self.label.setText(_translate("MainWindow", "Definir novo alarme:"))
